import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/errors/index.ts',
    'src/crypto/index.ts',
    'src/features/csrf/index.ts',
    'src/features/fingerprint/index.ts',
    'src/features/concurrency/index.ts',
    'src/features/audit/index.ts',
    'src/adapters/memory/index.ts',
    'src/adapters/cookie/index.ts',
    'src/adapters/redis/index.ts',
    'src/adapters/upstash/index.ts',
    'src/adapters/cloudflare-kv/index.ts',
    'src/adapters/cloudflare-d1/index.ts',
    'src/adapters/postgres/index.ts',
    'src/adapters/durable-object/index.ts',
    'src/frameworks/hono/index.ts',
    'src/frameworks/elysia/index.ts',
    'src/frameworks/next/index.ts',
    'src/frameworks/remix/index.ts',
    'src/frameworks/sveltekit/index.ts',
    'src/frameworks/express/index.ts',
    'src/frameworks/fastify/index.ts',
    'src/frameworks/h3/index.ts',
  ],
  format: ['esm'],
  target: 'node20',
  outDir: 'dist',
  dts: false,
  splitting: false,
  sourcemap: false,
  clean: true,
  treeshake: true,
});
